### ISSUE TITLE
error 500 accessing ghoto2server via local host or remotely.

### ISSUE THREAD

**Issue by stargeezer55** [mvmn/gp2srv#13]
I recently installed gphoto2 server using the tutorial on youtube. I the only thing I didn't do was set the pi up as a hotspot at this time as it was stated as being optional. Gphoto2 works just fine. 
I cannot get web access either on the localhost( raspberry pi 3/ raspbian) or another pc on the same internal network. Error 500 is reported which I understand is a generic error reported by web servers. 
netstat -tnlp | grep 8080 reports LISTEN.  
pi@raspberrypi:/ $ sudo netstat -tlnp | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      1214/java           

Any ideas would be most welcome. 
Thanks

**Comment by mvmn** [comment]
Error 500 means error on a server side. You need to provide error message that gphoto2-server produces in console when that happens.
How do you start it - via java -jar gphoto2-server.jar? Take the console output it produces when you get HTTP status 500 response, and copy-paste it here.

**Comment by stargeezer55** [comment]
Thanks for your prompt reply. Yes I start it as you described.  Problem with a link?
Hope this helps...

2019-02-25 16:15:07.729:INFO:oejs.Server:main: Started @4491ms
2019-02-25 16:15:07.730 - INFO: Starting server: done.
2019-02-25 16:15:59.061:WARN:oejs.ServletHandler:qtp10055096-13: Error for /
java.lang.UnsatisfiedLinkError: Unable to load library 'gphoto2': Native library (linux-arm/libgphoto2.so) not found in resource path ([file:/home/pi/gphoto-srv/gp2srv-2.8/GPhoto2Server-2.8.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:337)
        at x.mvmn.gphoto2.jna.Gphoto2Library.<clinit>(Gphoto2Library.java:26)
        at x.mvmn.jlibgphoto2.GP2Context.<init>(GP2Context.java:12)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
2019-02-25 16:16:00.571:WARN:oejs.ServletHandler:qtp10055096-9: Error for /favicon.ico
java.lang.NoClassDefFoundError: Could not initialize class x.mvmn.gphoto2.jna.Gphoto2Library
        at x.mvmn.jlibgphoto2.GP2Context.<init>(GP2Context.java:12)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
2019-02-25 16:15:07.729:INFO:oejs.Server:main: Started @4491ms
2019-02-25 16:15:07.730 - INFO: Starting server: done.
2019-02-25 16:15:59.061:WARN:oejs.ServletHandler:qtp10055096-13: Error for /
java.lang.UnsatisfiedLinkError: Unable to load library 'gphoto2': Native library (linux-arm/libgphoto2.so) not found in resource path ([file:/home/pi/gphoto-srv/gp2srv-2.8/GPhoto2Server-2.8.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:337)
        at x.mvmn.gphoto2.jna.Gphoto2Library.<clinit>(Gphoto2Library.java:26)
        at x.mvmn.jlibgphoto2.GP2Context.<init>(GP2Context.java:12)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
2019-02-25 16:16:00.571:WARN:oejs.ServletHandler:qtp10055096-9: Error for /favicon.ico
java.lang.NoClassDefFoundError: Could not initialize class x.mvmn.gphoto2.jna.Gphoto2Library
        at x.mvmn.jlibgphoto2.GP2Context.<init>(GP2Context.java:12)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.

**Comment by mvmn** [comment]
> Unable to load library 'gphoto2': Native library (linux-arm/libgphoto2.so)

That's the culprit. Where is the **libgphoto2.so** file located in your system? You'd have to provide special parameter with a path to it: `-Djna.library.path=/path/to/folder/with/libgphoto2.so`

**Comment by mvmn** [comment]
P.S. Alternatively use environment variable LD_LIBRARY_PATH to include path to libgphoto2.so folder

**Comment by stargeezer55** [comment]
Sorry for the tardy reply. Thanks for your help. I'm going to do a fresh install of raspbian and start over. I will let you you know if a couple of days. 
Thanks again!

**Comment by stargeezer55** [comment]
It works! SD card turns out to be corrupted. Reinstalled on new card and presto! Success! 
As a budding astro photgrapher I was searching for something that  I could control my camera settings and shutter release remotely from my phone/tablet. Next step will be to set the pi up as an AP.
Thank you for your help and prompt replies. Great work!

**Comment by mvmn** [comment]
Awesome
urw

**Comment by GrayFox-fra** [comment]
Hi Mykola,

After some years I wanted to use your app, so after installed [Java](https://linuxize.com/post/install-java-on-raspberry-pi/), [Gphoto2-Updater](https://github.com/gonzalo/gphoto2-updater) and your [last release](https://github.com/mvmn/gp2srv/releases/download/2.8/gp2srv-2.8.zip), I have the same error 500, here I past the status

pi@raspberrypi:~/Desktop/gp2srv-2.8 $ java -jar GPhoto2Server-2.8.jar
2021-12-29 16:12:46.945 - INFO: Initializing...
2021-12-29 16:12:48.000:INFO::main: Logging initialized @3446ms
Images download folder: /home/pi/gp2srv_images
2021-12-29 16:12:51.227 - INFO: Initializing: done.
2021-12-29 16:12:51.228 - INFO: Starting server...
2021-12-29 16:12:51.251:INFO:oejs.Server:main: jetty-9.3.12.v20160915
2021-12-29 16:12:52.318:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@a9f84e{/,null,AVAILABLE}
2021-12-29 16:12:52.550:INFO:oejs.AbstractConnector:main: Started ServerConnector@149ef58{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2021-12-29 16:12:52.557:INFO:oejs.Server:main: Started @8039ms
2021-12-29 16:12:52.558 - INFO: Starting server: done.
2021-12-29 16:13:06.757:WARN:oejs.ServletHandler:qtp15194609-9: /
x.mvmn.jlibgphoto2.exception.GP2Exception: GP_ERROR_IO_USB_CLAIM
        at x.mvmn.jlibgphoto2.util.GP2ErrorHelper.checkResult(GP2ErrorHelper.java:41)
        at x.mvmn.jlibgphoto2.GP2Camera.<init>(GP2Camera.java:114)
        at x.mvmn.jlibgphoto2.GP2Camera.<init>(GP2Camera.java:100)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:56)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)

Can you help me please?

**Comment by mvmn** [comment]
> x.mvmn.jlibgphoto2.exception.GP2Exception: GP_ERROR_IO_USB_CLAIM

This error says that USB is busy
So something is already connected to the camera, or the process doesn't have permissions to access USB.

Which operating system is this on?

**Comment by mvmn** [comment]
Possibly this is the same issue as https://askubuntu.com/questions/993876/gphoto2-could-not-claim-the-usb-device

Does `gphoto2 --capture-image` in terminal work for you?

**Comment by GrayFox-fra** [comment]
Oh amazing, now it's working!!!

Thankyou I couldn't find that process... ;)

**Comment by mvmn** [comment]
You're welcome

Please post what exactly did you do to make it work though

**Comment by GrayFox-fra** [comment]
Sure,

the solution it's in this [guide](https://askubuntu.com/questions/993876/gphoto2-could-not-claim-the-usb-device)

It turned out that that in fact there was `gvfs-gphoto2-volume-monitor process` in the background.

Run `ps aux | grep gphoto`, which might have output like:

```
pi    25802  2.1  0.1 302504  8736 ?        Ssl  13:10   0:00 /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
pi    25814  2.2  0.1 441508 11176 ?        Sl   13:10   0:00 /usr/lib/gvfs/gvfsd-gphoto2 --spawner :1.3 /org/gtk/gvfs/exec_spaw/21
pi    25835  0.0  0.0  22676  1096 pts/0    S+   13:10   0:00 grep --color=auto gphoto
```
First colums is PID (process id), kill them:

```
kill -9 25802
kill -9 25814
```

Now gphoto2 can now connect to camera !!!

**Comment by mvmn** [comment]
Nice
Thanks!
