### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path (GPhoto2Server-2.8.jar)

### ISSUE THREAD

**Issue by Protokollmaker** [mvmn/gp2srv#16]
I am typing to install the software but accross all versions (tested on: 2.8, 2.7, 2.6, 1.2) i get the error:
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path (GPhoto2Server-2.8.jar)
the next text is a bit diverent betwend verson on version 2.8:
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path (GPhoto2Server-2.8.jar)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:776)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
        at com.sun.jna.Native.<clinit>(Native.java:131)
        at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:82)
        at x.mvmn.gphoto2.jna.Gphoto2Library.<clinit>(Gphoto2Library.java:26)
        at x.mvmn.jlibgphoto2.GP2Context.<init>(GP2Context.java:12)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-05-06 17:28:02.373:WARN:oejs.ServletHandler:qtp1920387277-13: Error for /favicon.ico
java.lang.NoClassDefFoundError: Could not initialize class x.mvmn.gphoto2.jna.Gphoto2Library
        at x.mvmn.jlibgphoto2.GP2Context.<init>(GP2Context.java:12)
        at x.mvmn.gp2srv.web.servlets.CameraChoiceFilter.doFilter(CameraChoiceFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:523)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.base/java.lang.Thread.run(Thread.java:829)
^C2023-05-06 17:29:02.603:INFO:oejs.AbstractConnector:Thread-0: Stopped ServerConnector@5a9e11a4{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2023-05-06 17:29:02.607:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.s.ServletContextHandler@316bcf94{/,null,UNAVAILABLE}

on verson 2.8 i get the error by trying to connect to the webserver.
webserver says: Error 500

im runing version gphoto2 2.5.28 of gphoto2 and
libgphoto2      2.5.30 
libgphoto2_port 0.12.1

im typing runing it on debion in a docker contaniner and on a rasberry pi with the raspberry pi lite image

**Comment by mvmn** [comment]
> Native library (com/sun/jna/linux-aarch64/libjnidispatch.so) not found in resource path 

Looks like some JNA issue. Which Java runtime environment do you use?

**Comment by mvmn** [comment]
Looks like this should fix the problem for you: https://stackoverflow.com/questions/29505217/sun-jna-library-with-support-for-arm-64

**Comment by Protokollmaker** [comment]
Thanks for the quick reply
java -version  gave me:
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode)
I installed it with:  apt install openjdk-8-jdk

I tried the solution on the left but could not find the folder jniLibs. I obtained the libjnidispatch.so file. I typed putting it in libs in the  /arm64-v8a and without the folder but it didn't work
and i used find / -name jniLibs witch shoud have found the folder on the entire system but didn't.

**Comment by mvmn** [comment]
Interesting - you installed Java 8 but got Java 11. Maybe you have both, and your path points to the Java 11 by default.
Can you try with Java 8?

Also, can you try to specify the path to the folder where you've extracted the `libjnidispatch.so` file via the `java.library.path` system property?
E.g. `java -Djava.library.path=/folder/where/libjnidispatch.so/lies -jar GPhoto2Server-2.8.jar`

**Comment by Protokollmaker** [comment]
![image](https://user-images.githubusercontent.com/82887145/236643057-1a17f883-422b-486b-a3f2-c4c379a95804.png)
java 8 dosn't seem to be installed i only see java 11

and i type runing it with 
java -jar -Djava.library.path=/app/webfrontend/jniLibs/arm64-v8a/libjnidispatch.so  GPhoto2Server-2.8.jar
![image](https://user-images.githubusercontent.com/82887145/236643151-7d72a903-8cdf-4cca-9822-32e035842795.png)

but it still gives the same error 

I also tried it with the official image of openjdk:11 to see if it works there but no luck.

**Comment by Protokollmaker** [comment]
i installed it like the:
on devian image
apt update
apt install wget -y
apt install unzip -y
apt install openjdk-8-jdk
wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh
wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/.env
chmod +x ./gphoto2-updater.sh
./gphoto2-updater.sh 
hire I select option 2 
wget https://github.com/mvmn/gp2srv/releases/download/2.8/gp2srv-2.8.zip
mkdir -p /app/webfrontend
unzip gp2srv-2.8.zip -d /app/webfrontend
cd /app/webfrontend/gp2srv-2.8
chmod +x run.bat
./run.bat

**Comment by mvmn** [comment]
Which docker image do you use BTW?

**Comment by Protokollmaker** [comment]
debian
Edit: https://hub.docker.com/_/debian

**Comment by mvmn** [comment]
And what is the host OS and CPU?

**Comment by Protokollmaker** [comment]
odroid n2+
ubuntu  
lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  3
Socket(s):           2
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         2208.0000
CPU min MHz:         500.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

but i got the same error on my frends raspberry pi 3 b+ 
with raspberry pi os lite

**Comment by Protokollmaker** [comment]
i run 64bit os

**Comment by mvmn** [comment]
I'm checking on a Raspberry Pi, need to install LibGPhoto2. While this is in progress - I've noticed that apt install for openjdk-8-jdk requires sudo. But with sudo it did install JDK 8 into /usr/lib/jvm

**Comment by Protokollmaker** [comment]
root@ad6f062d29e5:/app/webfrontend/gp2srv-2.8# sudo apt install openjdk-8-jdk
bash: sudo: command not found
i am root  so sudo don't work

**Comment by Protokollmaker** [comment]
I also typ installing with with apt install default-jre -y
but same issue hier is my dockerfile:
FROM debian
RUN apt update
RUN apt install curl -y
RUN apt install wget -y
RUN apt install unzip -y

RUN apt install default-jre -y
RUN java -version
workdir /app
RUN wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh
RUN wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/.env
RUN chmod +x ./gphoto2-updater.sh
RUN printf '2\n' | ./gphoto2-updater.sh 
RUN wget https://github.com/mvmn/gp2srv/releases/download/2.8/gp2srv-2.8.zip
RUN mkdir -p /app/webfrontend
RUN unzip gp2srv-2.8.zip -d /app/webfrontend
workdir /app/webfrontend/gp2srv-2.8
COPY ./run.bat ./run1.bat
RUN chmod +x run1.bat
CMD [ "/app/webfrontend/gp2srv-2.8/run1.bat" ]

run1.bat 
#!/bin/bash
java -jar  GPhoto2Server-2.8.jar

**Comment by Protokollmaker** [comment]
I just checkt on play with docker and ther it worked link hier:
https://labs.play-with-docker.com/p/chbc1jie69v00088p3lg#chbc1jie_chbc1kie69v00088p3m0

**Comment by mvmn** [comment]
Seems like there is a need to upgrade JNA JAR to a newer version in order for it to work with the 64-bit version of ARM library.

I'll take a look to that when I have some free time, but no promises.

**Comment by mvmn** [comment]
For now try this workaround: download jna.jar from https://github.com/java-native-access/jna/blob/master/dist/jna.jar

Remove `jna-4.1.0.jar` from `lib` folder of GPhoto2Server and replace it with `jna.jar` downloaded from link above

Unpack GPhoto2Server.jar and change META-INF/MANIFEST.MF Class-Path part to have `lib/jna.jar` instead of `lib/jna-4.1.0.jar`

Pack it back and run

**Comment by Protokollmaker** [comment]
I think my frind alsow run it on a 64bit os on his rasbperry pi 3 b+ 
I switched to the recomended 32bit install of raspberry os 
but got anoter error 
pi@raspberrypi:~/gp2srv-2.8 $ sudo ./run.sh
2023-05-07 09:05:48.830 - INFO: Initializing...
2023-05-07 09:05:49.418:INFO::main: Logging initialized @1301ms
Images download folder: /root/gp2srv_images
2023-05-07 09:05:50.194 - INFO: Initializing: done.
2023-05-07 09:05:50.194 - INFO: Starting server...
2023-05-07 09:05:50.201:INFO:oejs.Server:main: jetty-9.3.12.v20160915
2023-05-07 09:05:50.484:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@19b00e0{/,null,AVAILABLE}
2023-05-07 09:05:50.543:INFO:oejs.AbstractConnector:main: Started ServerConnector@1d92581{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2023-05-07 09:05:50.545:INFO:oejs.Server:main: Started @2449ms
2023-05-07 09:05:50.545 - INFO: Starting server: done.
java: symbol lookup error: /usr/local/lib/libgphoto2.so: undefined symbol: gp_port_init_localedir, version LIBGPHOTO2_5_0



pi@raspberrypi:~/gp2srv-2.8 $ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Raspbian-1deb11u1rpt1)
OpenJDK Client VM (build 17.0.6+10-Raspbian-1deb11u1rpt1, mixed mode, emulated-client)

(and i typed changing the META-INF/MANIFEST.MF on the 64bit os but i think did somthing wrong.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/velocity/runtime/resource/util/StringResourceRepository)

**Comment by mvmn** [comment]
> symbol lookup error: /usr/local/lib/libgphoto2.so: undefined symbol: gp_port_init_localedir, version LIBGPHOTO2_5_0

This one means it found an old version of LibGphoto2 - 2.5.0, as it says in the log (current version seems to be 2.5.30). You just need to remove the old version, as the https://github.com/gonzalo/gphoto2-updater instructions say:
`sudo apt-get remove gphoto2 libgphoto2-6 libgphoto2-dev libgphoto2-l10n libgphoto2-port12`

**Comment by Protokollmaker** [comment]
I was a brand now install oft rasbperry pi os so i thowed i didn't have a old version (nuke a other os) but it works now 
Thanks. 
I owe you big times. 
If i can help you in some way let me know

**Comment by mvmn** [comment]
Glad to help

If you really want to help me though - please support Ukraine via foundations like Come Back Alive https://savelife.in.ua/en/ or https://www.razomforukraine.org

Thank you
