### ISSUE TITLE
error with preview/reading flles 

### ISSUE THREAD

**Issue by jcbconway** [mvmn/gp2srv#20]
Hello! I am having an issue with showing the preview and browsing photos. I am using the latest pre built jar file. I am having issues debugging this stack trace. Admittedly I have not pulled the source down/attempted to build myself for further debugging. 

The following error occurs when navigating to 'http://192.168.1.5:8080/browse' url. 

` pi@pi:~/gp2srv_0.01 $ sudo java -jar GPhoto2Server-0.0.1-SNAPSHOT.jar
2024-08-20 02:20:36.982 - INFO: Initializing...
2024-08-20 02:20:37.933 - INFO: Initializing: done.
2024-08-20 02:20:37.934 - INFO: Starting server...
2024-08-20 02:20:37.950:INFO:oejs.Server:jetty-7.6.15.v20140411
2024-08-20 02:20:38.178:INFO:oejsh.ContextHandler:started o.e.j.s.ServletContextHandler{/,null}
2024-08-20 02:20:38.315:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
2024-08-20 02:20:38.334 - INFO: Starting server: done.
2024-08-20 02:20:39.886 - ERROR:
java.lang.Exception: Unexpected line: #1     IMG_3486.JPG               rd  2110 KB image/jpeg 1724101438
        at x.mvmn.gp2srv.service.gphoto2.FileListParser.parseList(FileListParser.java:135)
        at x.mvmn.gp2srv.service.gphoto2.command.GP2CmdListFiles.submitRawStandardOutput(GP2CmdListFiles.java:26)
        at x.mvmn.gp2srv.service.gphoto2.GPhoto2CommandService.executeCommand(GPhoto2CommandService.java:17)
        at x.mvmn.gp2srv.web.servlets.CameraControlServlet.processRequestByPath(CameraControlServlet.java:194)
        at x.mvmn.gp2srv.web.servlets.CameraControlServlet.doGet(CameraControlServlet.java:172)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at java.base/java.lang.Thread.run(Thread.java:840)3.run(QueuedThreadPool.java:543))52)7)`

**Comment by mvmn** [comment]
GPhoto2Server-0.0.1-SNAPSHOT.jar - this seems like a VERY old version, why don't you upgrade to the latest one?

**Comment by jcbconway** [comment]
I feel very silly for not noticing that. I *thought* I had downloaded the latest 2.1.1 build. I will update and go from there.

**Comment by jcbconway** [comment]
I was able to get the 2.1.1 build working after updating to the latest libgphoto2 version.  Thank you.
